[package]
name = "spectrum"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
plotters = "0.3.5"

# Linfa dependencies
linfa = { version = "0.7.0", features = ["clustering"] }
linfa-clustering = "0.7.0"